### ISSUE TITLE
Meta: Consider disabling GitHub actions for draft PRs

### ISSUE THREAD

**Issue by ChrisRenfrow** [initiative-sh/initiative.sh#350]
In the interest of reducing email spam for failed builds, I looked into ways to avoid running GH actions for draft PRs and it seems [this is possible](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request).

I believe this is all that's required for any of the workflows that don't need to run until they're ready for review.

```yaml
on:
  pull_request:
    branches: [ main ]
    types: [ ready_for_review ]
```
